### PR TITLE
✨ Process Def List is now sorted

### LINKED ISSUE #7: Sort for all lists
Any list that is display should either have a fixed sort order or an option to set sort order.

### PR DESCRIPTION
**Pull request by Vyperus**
## What did you change?

This PR adds a basic sorting method for the processdef-list.
This Sorting method sorts lexicographical for the key.

Closes #7 

## How can others test the changes?

Save an already saved process in the Detail-View. The Process will now stay in the same place as before when reloading the List-View

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

**Comment by ppoetschke** [comment]
I don‘t think it‘s a good idea to sort client side as it requires to load all entities. There are options to do correct sorting - even together with pagination - in the backend.

**Comment by Vyperus** [comment]
I agree with you! But then we need to relocate the mentioned Issue. :)

**Comment by ppoetschke** [comment]
Not really because sort and query options should be implemented client side and passed through to the backend. They are already implemented in the backend.

**Comment by heikomat** [comment]
@ppoetschke even so this would still be more of a consumerClient issue, and less of a charon issue. The consumerClient needs to give charon the option to get a sorted list.

**Comment by ppoetschke** [comment]
Instead of only using limit and offset as params for `getProcessDefList`in `consumer_client` the attributes of `IPublicQueryOptions` of `core_contracts` should be implemented. IPublicQueryOptions already supports sorting on the backend correctly.
The orderBy option should be set by Charon and passed through by consumer_client. I consider setting a static orderBy option in consumer_client as anti pattern as it prevents sorting initiated by the user i.e. by clicking on a column header.
Please add appropriate issues in the involved repos if necessary.

**Pull request closed without merging**
